server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: parques
          uri: lb://service-parques
          predicates:
            - Path=/parques/**
          filters:
            - StripPrefix=1
        - id: utilizadores
          uri: lb://service-utilizadores
          predicates:
            - Path=/utilizadores/**
          filters:
            - StripPrefix=1
        - id: sessoes
          uri: lb://service-sessoes
          predicates:
            - Path=/sessoes/**
          filters:
            - StripPrefix=1
        - id: tarifas
          uri: lb://service-tarifas-faturacao
          predicates:
            - Path=/tarifas/**
          filters:
            - StripPrefix=1
        - id: reco
          uri: lb://service-reco-analytics
          predicates:
            - Path=/reco/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"