server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    loadbalancer:
      cache:
        enabled: true  # se tiveres Caffeine na classpath, usa-a
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 10s
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: [GET, POST, PATCH, PUT, DELETE, OPTIONS]
            allowedHeaders: "*"
            allowCredentials: false
      server:
        webflux:
          routes:
            - id: parques
              uri: lb://service-parques
              predicates:
                - Path=/parques/**
            - id: sessoes
              uri: lb://service-sessoes
              predicates:
                - Path=/sessoes/**
            - id: utilizadores
              uri: lb://service-utilizadores
              predicates:
                - Path=/utilizadores/**
            - id: tarifas
              uri: lb://service-tarifas-faturacao
              predicates:
                - Path=/tarifas/**
            - id: reco
              uri: lb://service-reco-analytics
              predicates:
                - Path=/reco/**

      # (Opcional) Retry autom√°tico em 5xx/timeout
      default-filters:
        - name: Retry
          args:
            retries: 2
            methods: [GET]
            statuses: [INTERNAL_SERVER_ERROR, BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT]

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka/}
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway,metrics"
  endpoint:
    gateway:
      enabled: true

