server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    loadbalancer:
      cache:
        enabled: true
    gateway:
      httpclient:
        connect-timeout: 3000
        timeout: 10s
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: [GET, POST, PATCH, PUT, DELETE, OPTIONS]
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: parques
          uri: lb://service-parques
          predicates:
            - Path=/parques/**
          filters:
            - AuthenticationFilter

        - id: sessoes
          uri: lb://service-sessoes
          predicates:
            - Path=/sessoes/**
          filters:
            - AuthenticationFilter

        - id: auth
          uri: lb://service-utilizadores
          predicates:
            - Path=/utilizadores/api/auth/**
          filters:

        - id: register
          uri: lb://service-utilizadores
          predicates:
            - Path=/utilizadores/api/utilizadores
            - Method=POST

        - id: utilizadores
          uri: lb://service-utilizadores
          predicates:
            - Path=/utilizadores/**
          filters:
            - AuthenticationFilter

        - id: tarifas
          uri: lb://service-tarifas-faturacao
          predicates:
            - Path=/tarifas/**
          filters:
            - AuthenticationFilter

        - id: reco
          uri: lb://service-reco-analytics
          predicates:
            - Path=/reco/**
          filters:
            - AuthenticationFilter

      default-filters:
        - name: Retry
          args:
            retries: 2
            methods: [GET]
            statuses:
              [
                INTERNAL_SERVER_ERROR,
                BAD_GATEWAY,
                SERVICE_UNAVAILABLE,
                GATEWAY_TIMEOUT,
              ]

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka/}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway,metrics"
  endpoint:
    gateway:
      enabled: true
